import * as fs from 'fs';
import * as path from 'path';
import { Store, Checkpoint, getHistory, resolveCheckpoint } from './store';

/**
 * Writes a CLAUDE.md file to the root of the project.
 * Claude Code reads this automatically on every session — so it always
 * knows what checkpoints exist and can act on rollback requests.
 */
function injectAiRules(filePath: string, instructionTitle: string): void {
  const markerStart = '<!-- VELA-START -->';
  const markerEnd = '<!-- VELA-END -->';
  const newContent = [
    markerStart,
    `## Vela Integration (${instructionTitle})`,
    'This codebase uses `vela` to snapshot working states and enable rollbacks.',
    'When the user asks to "roll back", "revert", or says they dislike a recent change:',
    '1. Refer to the list of checkpoints in `CLAUDE.md`.',
    '2. Find the matching codename (e.g., `glacier-add-dark-mode-7f3a`).',
    '3. Run: `npx vela restore <codename>` to perform the rollback automatically.',
    '4. Note: Do not manually edit or revert files if vela can restore the checkpoint.',
    markerEnd
  ].join('\n');

  let fileContent = '';
  try {
    if (fs.existsSync(filePath)) {
      fileContent = fs.readFileSync(filePath, 'utf8');
    }
  } catch {}

  const startIndex = fileContent.indexOf(markerStart);
  const endIndex = fileContent.indexOf(markerEnd);

  if (startIndex !== -1 && endIndex !== -1) {
    const updated = fileContent.slice(0, startIndex) + newContent + fileContent.slice(endIndex + markerEnd.length);
    fs.writeFileSync(filePath, updated, 'utf8');
  } else {
    const separator = fileContent ? '\n\n' : '';
    fs.writeFileSync(filePath, fileContent + separator + newContent, 'utf8');
  }
}

/**
 * Writes CLAUDE.md and injects instructions for Cursor, Copilot, and Windsurf.
 * This ensures any AI IDE/agent in use can discover checkpoints and perform rollbacks.
 */
export function writeClaudeMd(rootDir: string, store: Store): void {
  const history = getHistory(store);
  const manifestPath = path.join(path.resolve(rootDir), 'CLAUDE.md');

  const lines: string[] = [
    '<!-- AUTO-GENERATED by vela — do not edit manually -->',
    '# Vela Manifest',
    '',
    '> This file is read by Claude Code, Cursor, Copilot, Windsurf, Antigravity, and other AI IDEs/agents.',
    '> It contains a map of every tracked feature snapshot.',
    '> When the user says "roll back to X", find the codename below and',
    '> call `npx vela restore <codename>` or use the rollback instructions.',
    '',
    '## Current HEAD',
    '',
  ];

  if (store.head) {
    const head = store.checkpoints.find(c => c.id === store.head);
    if (head) {
      lines.push(`**Codename:** \`${head.codename}\``);
      lines.push(`**Intent:** ${head.intent}`);
      lines.push(`**Created:** ${head.createdAt}`);
      lines.push('');
    }
  } else {
    lines.push('_No checkpoints yet._', '');
  }

  lines.push('## Checkpoint History', '');
  lines.push('| # | Codename | Intent | Files | Created |');
  lines.push('|---|----------|--------|-------|---------|');

  history.forEach((cp, i) => {
    const fileCount = Object.keys(cp.files).length;
    const label = i === 0 ? `${cp.codename} ← HEAD` : cp.codename;
    lines.push(`| ${history.length - i} | \`${label}\` | ${cp.intent} | ${fileCount} | ${cp.createdAt.slice(0, 10)} |`);
  });

  lines.push('');
  lines.push('## Rollback Instructions for AI');
  lines.push('');
  lines.push('When the user asks to roll back to a feature or says they dislike a change:');
  lines.push('');
  lines.push('1. Match their description to a **Codename** in the table above');
  lines.push('2. Run: `npx vela restore <codename>`');
  lines.push('3. Confirm which files were restored and summarize what changed');
  lines.push('');
  lines.push('### Codename → File Map');
  lines.push('');

  for (const cp of history) {
    lines.push(`#### \`${cp.codename}\``);
    lines.push(`_${cp.description}_`);
    lines.push('');
    for (const [relPath, state] of Object.entries(cp.files)) {
      lines.push(`- \`${relPath}\` (${state.lines} lines, hash: \`${state.hash}\`)`);
    }
    if (cp.tags.length > 0) lines.push(`- Tags: ${cp.tags.map(t => `\`${t}\``).join(', ')}`);
    lines.push('');
  }

  lines.push('---');
  lines.push('_Generated by [vela](https://github.com/you/codebase-reader)_');

  const targets = store.targets ?? [];
  const writeAll = targets.length === 0;
  const resolvedRoot = path.resolve(rootDir);

  // CLAUDE.md
  if (writeAll || targets.some(t => ['claude', 'agy', 'codex'].includes(t))) {
    fs.writeFileSync(manifestPath, lines.join('\n'), 'utf8');
  }

  // Cursor rules
  if (writeAll || targets.includes('cursor')) {
    injectAiRules(path.join(resolvedRoot, '.cursorrules'), 'Cursor Rules');
  }

  // Windsurf rules
  if (writeAll || targets.includes('windsurf')) {
    injectAiRules(path.join(resolvedRoot, '.windsurfrules'), 'Windsurf Rules');
  }

  // Copilot instructions
  if (writeAll || targets.includes('copilot')) {
    const githubDir = path.join(resolvedRoot, '.github');
    try {
      fs.mkdirSync(githubDir, { recursive: true });
      injectAiRules(path.join(githubDir, 'copilot-instructions.md'), 'GitHub Copilot Rules');
    } catch {}
  }
}

/** 
 * Generates a rollback plan as structured JSON that any AI agent can parse.
 * This is what Claude Code / Cursor would read to perform the restore.
 */
export function generateRollbackPlan(
  checkpoint: Checkpoint,
  rootDir: string
): RollbackPlan {
  const ops: RollbackOp[] = [];

  for (const [relPath, state] of Object.entries(checkpoint.files)) {
    const fullPath = path.join(path.resolve(rootDir), relPath);
    const currentContent = fs.existsSync(fullPath)
      ? fs.readFileSync(fullPath, 'utf8')
      : null;

    if (currentContent === state.content) continue; // already matches

    const currentLines = currentContent?.split('\n') ?? [];
    const targetLines = state.content.split('\n');

    ops.push({
      file: relPath,
      absolutePath: fullPath,
      action: currentContent === null ? 'create' : 'overwrite',
      fromLines: currentLines.length,
      toLines: targetLines.length,
      contentPreview: targetLines.slice(0, 5).join('\n'),
    });
  }

  return {
    checkpointId: checkpoint.id,
    codename: checkpoint.codename,
    intent: checkpoint.intent,
    description: checkpoint.description,
    operations: ops,
    aiInstructions: buildAiInstructions(checkpoint, ops),
  };
}

export interface RollbackOp {
  file: string;
  absolutePath: string;
  action: 'overwrite' | 'create' | 'delete';
  fromLines: number;
  toLines: number;
  contentPreview: string;
}

export interface RollbackPlan {
  checkpointId: string;
  codename: string;
  intent: string;
  description: string;
  operations: RollbackOp[];
  aiInstructions: string;
}

function buildAiInstructions(checkpoint: Checkpoint, ops: RollbackOp[]): string {
  if (ops.length === 0) return 'No changes needed — files already match this checkpoint.';

  return [
    `To restore checkpoint \`${checkpoint.codename}\` ("${checkpoint.intent}"):`,
    '',
    ...ops.map((op, i) =>
      `${i + 1}. ${op.action === 'overwrite' ? 'Overwrite' : 'Create'} \`${op.file}\`` +
      ` (${op.fromLines} → ${op.toLines} lines)`
    ),
    '',
    'Execute: `npx vela restore ' + checkpoint.codename + '`',
  ].join('\n');
}
